### ISSUE TITLE
Physics engine discussion and checklist

### ISSUE THREAD

**Issue by DoctorVWA** [Factory-Rise/Factory-Rise#2]
## Checklist
- [ ] Decide which engine to use (write my own, [box2d](https://github.com/Bastacyclop/rust_box2d), [nphysics2](https://github.com/dimforge/nphysics), others...)
- [ ] Write a proper wrapper in [fr-physics](https://github.com/Factory-Rise/fr-physics) to be used in the engine
- [ ] Colision system
  - [ ] High-level wise configuration methods for boxed colision, that will be handled by the engine
  - [ ] Add to config or commandline parameters, similar to Source Engine's `noclip`
- [ ] Gravity by planet
  - [ ] Configurable and editable(?)
- [ ] Terrain friction depending on the block
  - [ ] Configurable
  - [ ] High-level wise configuration to be handled by the engine
- [ ] Real player movement, not just an stupid constant speed.
  - [ ] Acceleration
    - [ ] Configurable, editable and upgradable
  - [ ] Inertia
    - [ ] Configurable/editable
  - [ ] Max speed
    - [ ] Configurable, editable and upgradable
